# Generated by Django 2.2.2 on 2019-06-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Usuario',
        ),
    ]
